### ISSUE TITLE
Unable to load DLL 'SQLite.Interop.dll' error

### ISSUE THREAD

**Issue by benhaotang** [torum/BlogWrite#1]
Hi, I am using the 1.0.4.0 version from MS store on Windows 11 Arm 22H2, after importing the opml, I was greeted by this error for all my feeds.
![image](https://user-images.githubusercontent.com/50174724/219904746-6c0490c8-34db-46b8-86ec-9fc241482e14.png)

**Comment by torum** [comment]
Hi, thank you for reporting! 
It's strrange that you get the error after seemingly unrelated thing like importing an opml... 
let me do some research about this.
Thank you again.

**Comment by torum** [comment]
It turns out the library "System.Data.SQLite" does not support Arm architecture...
What I'm going to do is that I'll remove ARM version from package, so that Arm device will pick x86 or x64 when install the app. x86 or x64 app should run fine on Arm Windows 11's the emulator. 
 
So, I'm sorry but you have to uninstall the app and reinstall the app after I re-upload new version to the app store. I'll let you know here when I re-upload it.

Sorry for the inconvinience and thank you again for reporting.

**Comment by torum** [comment]
I just updated the app to v1.0.5 and submited to the MS app store. It may take a few hours to several days to be available. If you could checked to see if it works or not and report back, it would be great. Thank you in advance.

**Comment by benhaotang** [comment]
I have received the update, there is no more problem. Although the start time increases by 2-3 seconds, the overall performance is still very good. Thank you very much.

**Comment by torum** [comment]
Thank you!
